### ISSUE TITLE
Add list and hash implementation of uthash

### ISSUE THREAD

**Issue by retuxx** [JX7P/XwinTox#18]
Currently XWinTox uses its own implementation of list and dictionary (hashtable). I think it's reasonable to use already existing implementations instead of reinventing the wheel.  

[uthash](http://troydhanson.github.io/uthash/) provides the data structures  hash, list (single linked, and double linked), dynamic (in size) arrays and dynamic (in size) strings. The library is header only and consists of 4 files (one for each data structure). It is well tested and as far as i can see written in ansi C.  Each data structure is an optional module.

Unfortunately uthash does not provide locking by its own. My suggestion is to wrap around an interface which provides locking if needed. Wrapping uthash with an simple interface is reasonable anyway, because it allows changing the backend if needed. Some code for read/write locks using pthread can be found at [liblist](https://github.com/mellowcandle/liblist/blob/master/src/llist.c).

**Comment by JX7P** [comment]
Evaluation of libuthash in another project revealed that it suffers from some unusual bugs which are difficult to trace. As a result I've made the decision to overhaul my own ADTs instead.
