### ISSUE TITLE
Licence

### ISSUE THREAD

**Issue by JX7P** [JX7P/XwinTox#20]
XwinTox was first licenced under the PPL (which was designed to address loopholes in copyleft), but I changed this after learning that the PPL is GPLv3-incompatible.

My basic ethical framework on software is similar to that explained by Stallman and the FSF, but with an addition:
* I don't believe that it is ethical for corporations to profit in any way from using in a commercial capacity a work that was created by the Commons.

As such, the permissive licences are, I feel, not suited to XwinTox. The GPLv3+ is really the minimum for me in terms of the level of freedom-protection that it offers. 

Still, the GPLv3+ is lacking in a few respects. The ASP (Application Service Provider) loophole is the most significant one; this is addressed by the AGPLv3, which I have learnt is GPLv3-compatible, its provisions applying only to the AGPLv3-written part of a work, and not to the GPLv3-written part.

Having said that, some have raised concerns that the AGPLv3 is overly complicated to follow. If we can't find a way to reduce the impact of that, we'll have to go with something else, almost certainly vanilla GPLv3.

**Comment by IRIXUser** [comment]
@Jookia I hope you don't mind if I tag you in this, since you seem to be well-versed in the limitations and requirements of free software licencing.

**Comment by retuxx** [comment]
Btw. the casual file name for licenses on Github is "LICENSE" instead of "CPYRIGHT"

**Comment by JX7P** [comment]
Done.
